| MODULE-SYSTEM.F1-IMPORTS.01 | FAIL |[MODULE-SYSTEM.F1-IMPORTS.01](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.01) | (assertEqual ((let $x (get-atoms &self) (get-type $x)))) | ((hyperon::space::DynSpace) (hyperon::space::DynSpace) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (DocInformal) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (()) (DocInformal) (()) (()) (DocInformal) (()) (()) (DocInformal) (()) (()) (DocInformal) (()) (()) (DocInformal) (()) (()) (()) (()) (()) (DocInfor...(3466) | ((hyperon::space::DynSpace) (hyperon::space::DynSpace)) | 20.842739000000776 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.02 | PASS |[MODULE-SYSTEM.F1-IMPORTS.02](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.02) | (assertEqual (if (> 1 2) 1 2)) | (2) | (2) | 0.002223999999273474 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-MODULEA.03 | PASS |[MODULE-SYSTEM.F1-MODULEA.03](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-MODULEA.03) | (assertEqual (+ 1 2)) | (3) | (3) | 0.0034860000006631253 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.04 | FAIL |[MODULE-SYSTEM.F1-IMPORTS.04](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.04) | (assertEqual (let $x (collapse (get-atoms &m)) (contains $x is-space))) | () | (True) | 0.011982000000188009 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.05 | PASS |[MODULE-SYSTEM.F1-IMPORTS.05](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.05) | (assertEqual (match &m (= (f 2) $x) $x)) | ((g 3)) | ((g 3)) | 0.002694999999164338 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-MODULEA.06 | PASS |[MODULE-SYSTEM.F1-MODULEA.06](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-MODULEA.06) | (assertEqual (+ 1 2)) | (3) | (3) | 0.0027650000014034504 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.07 | PASS |[MODULE-SYSTEM.F1-IMPORTS.07](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.07) | (assertEqual (g 2)) | (102) | (102) | 0.0029050000023289613 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.08 | PASS |[MODULE-SYSTEM.F1-IMPORTS.08](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.08) | (assertEqual (f 2)) | (103) | (103) | 0.00298499999829005 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.09 | PASS |[MODULE-SYSTEM.F1-IMPORTS.09](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.09) | (assertEqual (let $a (collapse (get-atoms &self)) (contains $a is-corelib))) | (True) | (True) | 0.0028649999990193464 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.10 | PASS |[MODULE-SYSTEM.F1-IMPORTS.10](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.10) | (assertEqual (if (> 1 2) 1 2)) | (2) | (2) | 0.0019130000019629279 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.11 | PASS |[MODULE-SYSTEM.F1-IMPORTS.11](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.11) | (assertEqual (g 2)) | (102) | (102) | 0.002835000000089849 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.12 | PASS |[MODULE-SYSTEM.F1-IMPORTS.12](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.12) | (assertEqual (f 2)) | (103) | (103) | 0.0018330000024491255 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.13 | PASS |[MODULE-SYSTEM.F1-IMPORTS.13](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.13) | (assertEqualToResult (dup 2)) | (102 12) | (12 102) | 0.07336699999882512 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.14 | PASS |[MODULE-SYSTEM.F1-IMPORTS.14](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.14) | (assertEqual (g 2)) | (102) | (102) | 0.001934000000147762 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.15 | PASS |[MODULE-SYSTEM.F1-IMPORTS.15](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.15) | (assertEqual (f 2)) | (103) | (103) | 0.001784000001947561 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-IMPORTS.16 | PASS |[MODULE-SYSTEM.F1-IMPORTS.16](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#MODULE-SYSTEM.F1-IMPORTS.16) | (assertEqualToResult (dup 2)) | (102 12) | (12 102) | 0.05176699999864809 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| WHOLE-TESTS.module-system.f1_imports | PASS | [WHOLE-TESTS.module-system.f1_imports](file://./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html#WHOLE-TESTS.module-system.f1_imports) | ./mettalog '--output=./reports/tests_output/baseline-compat/' --timeout=40 --html --repl=false  --test "tests/baseline_compat/module-system/f1_imports.metta" --halt=true | 7 | 7 | 32 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_imports.metta.html |
| MODULE-SYSTEM.F1-MODULEA.01 | PASS |[MODULE-SYSTEM.F1-MODULEA.01](https://trueagi-io.github.io/metta-wam/./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_moduleA.metta.html#MODULE-SYSTEM.F1-MODULEA.01) | (assertEqual (+ 1 2)) | (3) | (3) | 0.003335999999798389 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_moduleA.metta.html |
| WHOLE-TESTS.module-system.f1_moduleA | PASS | [WHOLE-TESTS.module-system.f1_moduleA](file://./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_moduleA.metta.html#WHOLE-TESTS.module-system.f1_moduleA) | ./mettalog '--output=./reports/tests_output/baseline-compat/' --timeout=40 --html --repl=false  --test "tests/baseline_compat/module-system/f1_moduleA.metta" --halt=true | 7 | 7 | 10 | ./reports/tests_output/baseline-compat//tests/baseline_compat/module-system/f1_moduleA.metta.html |
