name: CI Job to Generate JUnit Reports with Diff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install junit2html
      run: |
        pip install junit2html

    - name: Make Shell Script Executable
      run: chmod +x scripts/run_commit_tests.sh

    - name: Run Shell Script to Generate Input File
      run: |
        ./scripts/run_commit_tests.sh

    - name: Run JUnit Report Generation Script
      run: |
        python scripts/into_junit.py /tmp/SHARED.UNITS > junit.xml

    - name: Convert JUnit XML to Standard HTML Report
      continue-on-error: true  # Continue to the next step even if this one fails
      run: |
        junit2html junit.xml junit-standard-report.html

    - name: Convert JUnit XML to Matrix HTML Report
      continue-on-error: true  # Continue to the next step even if this one fails
      run: |
        junit2html --report-matrix junit-matrix-report.html junit.xml

    - name: Upload JUnit XML Report
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: junit.xml

    - name: Upload Standard HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: junit-standard-html-report
        path: junit-standard-report.html

    - name: Upload Matrix HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: junit-matrix-html-report
        path: junit-matrix-report.html

    - name: Display JUnit Test Results
      uses: dorny/test-reporter@v1
      with:
        name: 'JUnit Results'
        path: 'junit.xml'
        reporter: 'java-junit'  # Correct reporter type for JUnit XML
        fail-on-error: false  # Do not fail the job if tests fail

    - name: Compare JUnit Test Results with mikepenz
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: junit.xml
        compare_to_previous: true
        fail_on_failure: false  # Do not fail the job if tests fail

    - name: Diff JUnit Test Results
      uses: Juit/junit-diff@v1.0.2
      with:
        base-junit: junit-report/base.xml  # Adjust to your previous report location
        head-junit: junit.xml  # The current test report
        output: junit-diff-report.html

    - name: Upload JUnit Diff Report
      uses: actions/upload-artifact@v3
      with:
        name: junit-diff-html-report
        path: junit-diff-report.html

    - name: Display HTML Report Information
      run: |
        echo "Standard, matrix, and diff HTML reports are available as artifacts. JUnit test comparison reports are also available."
